// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using blanchard_web_api;

#nullable disable

namespace blanchard_web_api.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240115160618_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("blanchard_web_api.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationInSecond")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistName = "David Bowie",
                            DurationInSecond = 202,
                            Title = "Life On Mars?"
                        },
                        new
                        {
                            Id = 2,
                            ArtistName = "Manau",
                            DurationInSecond = 285,
                            Title = "La tribu de Dana"
                        },
                        new
                        {
                            Id = 3,
                            ArtistName = "Jean-Jacques Goldman",
                            DurationInSecond = 237,
                            Title = "Au bout de mes rêves"
                        },
                        new
                        {
                            Id = 4,
                            ArtistName = "Indochine",
                            DurationInSecond = 326,
                            Title = "La vie est belle"
                        },
                        new
                        {
                            Id = 5,
                            ArtistName = "Florian Montagne",
                            DurationInSecond = 122,
                            Title = "Moi, je viens de Narbonne"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
