// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using blanchard_web_api;

#nullable disable

namespace blanchard_web_api.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("blanchard_web_api.Entities.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "David Bowie"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Manau"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Jean-Jacques Goldman"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Indochine"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Florian Montagne"
                        });
                });

            modelBuilder.Entity("blanchard_web_api.Entities.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationInSecond")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistId = 1,
                            ArtistName = "David Bowie",
                            DurationInSecond = 202,
                            Title = "Life On Mars?"
                        },
                        new
                        {
                            Id = 2,
                            ArtistId = 2,
                            ArtistName = "Manau",
                            DurationInSecond = 285,
                            Title = "La tribu de Dana"
                        },
                        new
                        {
                            Id = 3,
                            ArtistId = 3,
                            ArtistName = "Jean-Jacques Goldman",
                            DurationInSecond = 237,
                            Title = "Au bout de mes rêves"
                        },
                        new
                        {
                            Id = 4,
                            ArtistId = 4,
                            ArtistName = "Indochine",
                            DurationInSecond = 326,
                            Title = "La vie est belle"
                        },
                        new
                        {
                            Id = 5,
                            ArtistId = 5,
                            ArtistName = "Florian Montagne",
                            DurationInSecond = 122,
                            Title = "Moi, je viens de Narbonne"
                        },
                        new
                        {
                            Id = 6,
                            ArtistId = 4,
                            ArtistName = "Indochine",
                            DurationInSecond = 300,
                            Title = "J'ai demandé à la lune"
                        });
                });

            modelBuilder.Entity("blanchard_web_api.Entities.Track", b =>
                {
                    b.HasOne("blanchard_web_api.Entities.Artist", "Artist")
                        .WithMany("Tracks")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("blanchard_web_api.Entities.Artist", b =>
                {
                    b.Navigation("Tracks");
                });
#pragma warning restore 612, 618
        }
    }
}
